//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public string nro_tarjeta { get; set; }
        public string fecha { get; set; }
        public string ccv { get; set; }
        public Nullable<decimal> saldo { get; set; }
    }
}
